version: '3.8'

volumes:
  keycloak-flutter-postgres-data:
    driver: local
    
services:
  keycloak-flutter-nginx:
    image: nginx
    depends_on:
      - keycloak-flutter
      - keycloak-flutter-ui
  keycloak-flutter-ui:
    image: "keycloakflutterui:dev"
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
  keycloak-flutter-postgres:
    image: postgres
    volumes:
      - keycloak-flutter-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak-flutter:
    image: quay.io/keycloak/keycloak:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .data/keycloak:/opt/keycloak/data/h2/
    command:
      - start-dev
      - --http-port=80
      - --proxy edge
    environment:
      DB: postgres
      KC_DB_URL: 'jdbc:postgresql://keycloak-flutter-postgres:5432/keycloak'
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB: postgres
      KEYCLOAK_STATISTICS: all
      KEYCLOAK_LOGLEVEL: DEBUG
      PROXY_ADDRESS_FORWARDING: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: change_me
    depends_on:
      - keycloak-flutter-postgres    