version: '3.8'

services:
  keycloak-flutter-ui:
    environment:
      TARGET_ENV: development
  keycloak-flutter-nginx:
    volumes:
      - ./appbuild/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./appbuild/nginx/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./appbuild/nginx/localhost.key:/etc/ssl/private/localhost.key
    ports:
      - "5553:443"
  keycloak-flutter-postgres:
    ports:
      - "5552:5432"
  keycloak-flutter:
    volumes:
    - ./appbuild/keycloak:/opt/keycloak/data/import:ro
    command:
      - start-dev
      - --http-port=80
      - --proxy edge
      - --import-realm
    ports:
      - "8081:80"
